metricsapp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index),
    url(r'^sprint/(?P<sprint_index>[0-9]+)$', views.index),
    url(r'^team/(?P<team_name>\w+)$', views.index),
    url(r'^sprint/(?P<sprint_index>[0-9]+)/team/(?P<team_name>\w+)$', views.index, name='index'),
	url(r'^compare$', views.compare),
	url(r'^compare/sprint/(?P<sprint_index>[0-9]+)$', views.compare, name='compare'),
	url(r'^deactivate$', views.deactivate, name='deactivate'),
	url(r'^latest-sprint-badge/$', views.latest_sprint_badge),
	url(r'^latest-sprint-badge/team/(?P<team_name>\w+)$', views.latest_sprint_badge, name='badge'),
]

scrumlint/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'scrumlint.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('metricsapp.urls')),
]

metricsapp/models.py
import json
from django.db import models
from django.utils import timezone
from metricsapp.data import result_data
from jsonfield import JSONField
from model_utils.managers import InheritanceManager

from metricsapp.settings import conf

class Metric(models.Model):

	@classmethod
	def rate(cls, list_of_metrics, sprint):
		rating = 0
		max_rating = 0
		for metric in list_of_metrics:
			metric_results = metric.get_results(sprint)
			rating += metric_results['score'] * metric.severity
			max_rating += 100 * metric.severity
		result = (rating/max_rating)*100
		return round(result, 2) 

	#Enables returning subclasses via select_subclasses()
	objects = InheritanceManager()

	name = models.CharField(max_length=50)
	description = models.CharField(max_length=2000)
	explanation = models.TextField(blank=True)
	query = models.CharField(max_length=2000)
	endpoint = models.CharField(max_length=200)
	results = JSONField(null=True)
	last_query = models.DateTimeField(null=True, blank=True)
	HIGH = 1.5
	NORMAL = 1.0
	LOW = 0.5
	SEVERITY_CHOICES = (
		(HIGH, 'High (1.5x)'),
		(NORMAL, 'Normal (1.0x)'),
		(LOW, 'Low (0.5x)'),
	)
	severity = models.FloatField(choices=SEVERITY_CHOICES,
								default=NORMAL)

	def __str__(self):
		return self.name

	def _run_query(self):
		return result_data[self.name]

	def _process(self, query_data):
		data = query_data['results'][0]
		result = {}
		result['rows'] = []
		for row in data['data']:
			result['rows'].append(row['row'])
		result['columns'] = data['columns']
		return result

	def _calculate_score(self, *args, **kwargs):
		return 50*self.severity

	def run(self):
		self.results = self._process(self._run_query())
		self.last_query = timezone.now()
		self.save()

	def score_rating(self, score):
		if score >= 75:
			return 'good'
		if score <= 25:
			return 'bad'
		return 'ok'

	def get_results(self, *args, **kwargs):
		score = self._calculate_score()
		rating = self.score_rating(score)
		return {'data':self.results, 'score':score, 'rating':rating}


class SprintMetric(Metric):
	def _run_query(self, sprint):
		return result_data[self.name + ' ' + sprint]

	def run(self):
		results = {}
		for sprint in conf.sprints:
			results[sprint] = self._process(self._run_query(sprint))
		self.results = results
		self.last_query = timezone.now()
		self.save()

	def get_results(self, sprint=conf.sprints[-1], *args, **kwargs):
		if isinstance(self.results, str):
			results = json.loads(self.results)
			print('GOT A STRING, WANTED A DICT')
		else:
			results = self.results
		score = self._calculate_score(sprint)
		rating = self.score_rating(score)
		return {'data':results[sprint], 'score':score, 'rating':rating}

class DailyUserStoryThroughput(SprintMetric):
	def _calculate_score(self, sprint=conf.sprints[-1]):
		SCORE_COLUMN = 'USperDev'
		UPPER_BOUND = 10
		LOWER_BOUND = 0.2
		
		if isinstance(self.results, str):
			results = json.loads(self.results)
			print('GOT A STRING, WANTED A DICT')
		else:
			results = self.results
		results = results[sprint]
		
		score_index = results['columns'].index(SCORE_COLUMN)
		value = results['rows'][0][score_index]
		
		if value > UPPER_BOUND or value < LOWER_BOUND:
			return 25
		r = 80 + (value*5)
		return r if r<=100 else 100

class JustInTimeDevelopment(SprintMetric):
	def _calculate_score(self, sprint=conf.sprints[-1]):
		SCORE_COLUMN = 'Percentage'
		UPPER_BOUND = 0.3
		
		if isinstance(self.results, str):
			results = json.loads(self.results)
			print('GOT A STRING, WANTED A DICT')
		else:
			results = self.results
		results = results[sprint]
		
		score_index = results['columns'].index(SCORE_COLUMN)
		value = results['rows'][0][score_index]

		if value > UPPER_BOUND:
			return 20
		r = 100 - (value*300)
		return r if r >= 0 else 0

metricsapp/models/base.py
import json
from django.db import models
from django.utils import timezone
from ..data import result_data
from jsonfield import JSONField
from model_utils.managers import InheritanceManager
import requests

from ..settings import conf

class Category(models.Model):
	name = models.CharField(max_length=50)

	def rate(self, sprint, team):
		return Metric.rate(self.metric_set.filter(active=True).select_subclasses(), sprint, team)

	def __str__(self):
		return self.name

	def is_empty(self):
		return not bool(self.metric_set.filter(active=True).count())

	class Meta:
		ordering = ('name',)
		verbose_name_plural = "categories"

class Metric(models.Model):

	@classmethod
	def rate(cls, list_of_metrics, sprint, team):
		rating = 0
		max_rating = 0
		for metric in list_of_metrics:
			metric_results = metric.summary(sprint, team)
			rating += metric_results['score'] * metric.severity
			max_rating += 100 * metric.severity
		result = (rating/max_rating)*100
		return round(result, 2) 

	#Enables returning subclasses via select_subclasses()
	objects = InheritanceManager()

	categories = models.ManyToManyField(Category)
	name = models.CharField(max_length=50)
	description = models.CharField(max_length=2000)
	explanation = models.TextField(blank=True)
	query = models.TextField()
	endpoint = models.CharField(max_length=200)
	results = JSONField(null=True)
	last_query = models.DateTimeField(null=True, blank=True)
	active = models.BooleanField(default=True)
	HIGH = 1.5
	NORMAL = 1.0
	LOW = 0.5
	VERY_LOW = 0.2
	INFO = 0
	SEVERITY_CHOICES = (
		(HIGH, 'High'),
		(NORMAL, 'Normal'),
		(LOW, 'Low'),
		(VERY_LOW, 'Very Low'),
		(INFO, 'Informational'),
	)
	severity = models.FloatField(choices=SEVERITY_CHOICES,
								default=NORMAL)

	def __str__(self):
		return self.name

	def _run_query(self):
		raise NotImplemented

	def _calculate_score(self, *args, **kwargs):
		raise NotImplemented

	def run(self):
		self.results = self._process(self._run_query())
		self.last_query = timezone.now()
		self.save()

	def summary(self, *args, **kwargs):
		score = self._calculate_score()
		return {'data':self.results, 'score':score}


class SprintMetric(Metric):
	def _run_query(self, sprint, team):
		payload = {
			"statements" : [ {
				"statement" : self.query.format(
								sprint=sprint,
								team=team['team_name'],
								label=team['label'],
								sprint_list=', '.join(["'"+s+"'" for s in conf.sprints])
							  )
			} ]
		}
		headers = {'Accept': 'application/json; charset=UTF-8', 'Content-Type': 'application/json'}
		r = requests.post(self.endpoint, data=json.dumps(payload), headers=headers)

		print(sprint, team['name'], r.text[:100])
		data = r.json()
		errors = data.get('errors')
		if errors:
			print('ERROR:', errors)

		return data

	def _process(self, query_data):
		data = query_data['results'][0]
		result = {}
		result['rows'] = []
		for row in data['data']:
			result['rows'].append(row['row'])
		result['columns'] = data['columns']
		return result

	def run(self):
		results = {}
		for sprint in conf.sprints:
			results[sprint] = {}
			for team in conf.teams:
				results[sprint][team['name']] = self._process(self._run_query(sprint, team))
		self.results = results
		self.last_query = timezone.now()
		self.save()

	def _result_getter(self, sprint, team):
		# https://github.com/bradjasper/django-jsonfield/issues/101
		if (isinstance(self.results, str) or isinstance(self.results, unicode)):
			results = json.loads(self.results)
		else:
			results = self.results
		return results[sprint][team['name']]

	def summary(self, sprint, team, *args, **kwargs):
		data = self._result_getter(sprint, team)
		score = self._calculate_score(sprint, team)
		return {'data': data, 'score':score}

	def get_value(self, sprint, team, column):
		results = self._result_getter(sprint, team)
		try:
			score_index = results['columns'].index(column)
		except ValueError:
			return None
		rows = results['rows']
		if rows:
			value = rows[0][score_index]
		else:
			value = None
		return value


class PercentMetric(SprintMetric):
	def _calculate_score(self, sprint, team):
		SCORE_COLUMN = 'Percentage'

		value = self.get_value(sprint, team, SCORE_COLUMN)
		if value is None:
			value = 0

		r = 100-(value*100)
		return r if r>0 else 0

metricsapp/models/commits_per_dev.py
from .base import SprintMetric

class CommitsPerDev(SprintMetric):
	def _calculate_score(self, sprint, team):
		SCORE_COLUMN = 'CommitsperDev'
		
		value = self.get_value(sprint, team, SCORE_COLUMN)
		if value is None:
			value = 0
		
		# >12 commits gets you 100
		r = value*8.5
		return r if r<100 else 100

metricsapp/models/daily_user_story_throughput.py
from .base import SprintMetric
from ..settings import conf
import json

class DailyUserStoryThroughput(SprintMetric):
	def _calculate_score(self, sprint, team):
		SCORE_COLUMN = 'USperDev'
		UPPER_BOUND = 10
		LOWER_BOUND = 0.2
		
		value = self.get_value(sprint, team, SCORE_COLUMN)
		if value is None:
			value = 0
		
		if value > UPPER_BOUND or value < LOWER_BOUND:
			return 25
		r = 80 + (value*5)
		return r if r<=100 else 100

metricsapp/models/forgotten_ones.py
from .base import SprintMetric
from ..settings import conf
import json

class ForgottenOnes(SprintMetric):
	def _calculate_score(self, sprint, team):
		SCORE_COLUMN = 'Percentage'
		UPPER_BOUND = 0.1

		value = self.get_value(sprint, team, SCORE_COLUMN)
		if value is None:
			value = 0
		r = 100 - (value*400)
		return r if r >= 0 else 0

metricsapp/models/just_in_time_development.py
from .base import SprintMetric
from ..settings import conf
import json

class JustInTimeDevelopment(SprintMetric):
	def _calculate_score(self, sprint, team):
		SCORE_COLUMN = 'Percentage'
		UPPER_BOUND = 0.3
		
		value = self.get_value(sprint, team, SCORE_COLUMN)
		if value is None:
			value = 0

		if value > UPPER_BOUND:
			return 20
		r = 100 - (value*300)
		return r if r >= 0 else 0

metricsapp/models/monster_stories.py
from .base import SprintMetric

class MonsterStories(SprintMetric):
	def _calculate_score(self, sprint, team):
		SCORE_COLUMN = 'IssueCount'
		
		value = self.get_value(sprint, team, SCORE_COLUMN)
		if value is None:
			value = 0

		# 11 incidents gets you a 50 rating
		r = 100-(value*8)
		return 0 if r<0 else r

metricsapp/models/personal_code_ownership.py
from .base import SprintMetric

class PersonalCodeOwnership(SprintMetric):
	def _calculate_score(self, sprint, team):
		data = self._result_getter(sprint, team)
		amount = len(data['rows'])

		# 11 incidents gets you a 50 rating
		r = 100-(amount*4.84)
		return 0 if r<0 else r

metricsapp/models/speedy_prs.py
from .base import SprintMetric

class SpeedyPRs(SprintMetric):
	def _calculate_score(self, sprint, team):
		SCORE_COLUMN = 'Percentage'
		
		value = self.get_value(sprint, team, SCORE_COLUMN)
		if value is None:
			value = 0
		
		r = 100-(value*100)
		return r if r>0 else 0

metricsapp/models/untested_complexity.py
from .base import SprintMetric

class UntestedComplexity(SprintMetric):
	def _calculate_score(self, sprint, team):
		SCORE_COLUMN = 'Percentage'
		
		value = self.get_value(sprint, team, SCORE_COLUMN)
		if value is None:
			value = 0
		
		r = 100-(value*100*2.3)
		return r if r>0 else 0

metricsapp/views.py
from django.shortcuts import render
from .models import Metric, Category
from .settings import conf
from .templatetags.neo4jformat import floor_to_multiple
import requests

from django.http import JsonResponse, HttpResponseNotAllowed, HttpResponseBadRequest, HttpResponse

def group_by(queryset, attrib):
	result = []
	for element in queryset:
		group = getattr(element, attrib).all()
		for ele in group:
			match = [r for r in result if r.get(attrib) == ele]
			if match:
				for m in match:
					m['items'].append(element)
			else:
				result.append({attrib:ele, 'items':[element]})
	return result

# Obligatory comment on how the author is aware of
# the code's shortcomings, but blames this on the
# lack of time
def index(request, sprint_index=None, team_name=None):
	if team_name is None:
		team_name = conf.teams[0]["name"]
	if sprint_index is None:
		sprint_index = len(conf.sprints)
	team = [team for team in conf.teams if team["name"] == team_name][0]
	sprint_index = int(sprint_index)
	sprint = conf.sprints[sprint_index-1]
	all_metrics = Metric.objects.filter(active=True).select_subclasses()
	categories_list = group_by(all_metrics, 'categories')
	chart_radar_labels = []
	chart_radar_data = []
	for cat in categories_list:
		metrics_data = []
		for metric in cat['items']:
			previous_scores = [metric.summary(s,team)['score'] for s in conf.sprints[:sprint_index]]
			metrics_data.append( (metric, metric.summary(sprint, team), previous_scores) )
		cat['metrics'] = metrics_data
		score = cat['categories'].rate(sprint, team)
		cat['score'] = score
		chart_radar_data.append(score)
		chart_radar_labels.append(str(cat['categories'].name))
	sprint_scores = [Metric.rate(all_metrics, s, team) for s in conf.sprints[:sprint_index]]

	context = {	
		'categories_list': categories_list, 
		'current_sprint': sprint,
		'current_sprint_index': sprint_index,
		'sprint_list': conf.sprints,
		'current_team': team,
		'team_list': conf.teams,
		'current_sprint_score': Metric.rate(all_metrics, sprint, team),
		'chart_overall_labels': list(conf.sprints[:sprint_index]),
		'chart_overall_data': sprint_scores,
		'chart_radar_data': chart_radar_data,
		'chart_radar_labels': chart_radar_labels
	}
	
	return render(request, 'metricsapp/index.html', context)

def compare(request, sprint_index=None):
	if sprint_index is None:
		sprint_index = len(conf.sprints)
	sprint_index = int(sprint_index)
	sprint = conf.sprints[sprint_index-1]

	selected_team_names = request.GET.getlist('team', [])
	all_teams = conf.teams
	if selected_team_names:
		current_teams = [t for t in all_teams if t['name'] in selected_team_names]
	else:
		current_teams = all_teams

	# Line chart of ScrumLint score over sprints of selected teams
	all_metrics = Metric.objects.filter(active=True).select_subclasses()
	line_chart_data = []
	for team in current_teams:
		scores = [Metric.rate(all_metrics, s, team) for s in conf.sprints[:sprint_index]]
		line_chart_data.append( (team, scores) )

	# Radar chart of categories for each team
	categories = [c for c in Category.objects.all() if not c.is_empty()]
	radar_chart_data = []
	for team in current_teams:
		cat_scores = [c.rate(sprint, team) for c in categories]
		radar_chart_data.append( (team, cat_scores ) )
	category_names = [str(c.name) for c in categories]

	# Line charts of individual metrics over sprints of selected teams
	metrics_chart_data = []
	for metric in all_metrics:
		team_scores = []
		for team in current_teams:
			metrics_scores = [metric.summary(s,team)['score'] for s in conf.sprints[:sprint_index]]
			team_scores.append( (team, metrics_scores) )
		metrics_chart_data.append( (metric, team_scores) )

	context = {
		'sprint_list': conf.sprints,
		'current_sprint': sprint,
		'current_sprint_index': sprint_index,
		'team_list': all_teams,
		'current_parameters': request.GET.urlencode(),
		'selected_teams': current_teams,
		'line_chart_data': line_chart_data,
		'line_chart_labels': list(conf.sprints[:sprint_index]),
		'radar_chart_data': radar_chart_data,
		'radar_chart_labels': category_names,
		'metrics_chart_data': metrics_chart_data,
	}
	return render(request, 'metricsapp/compare.html', context)


from django.views.decorators.csrf import csrf_exempt
# See https://docs.djangoproject.com/en/1.8/ref/csrf/
# for the proper way to handle CSRF & POST
@csrf_exempt
def deactivate(request):
	# request.POST can be {} on POST request
	if request.method != "POST":
		message = '405 - Method Not Allowed. Only POST is supported.'
		# first constructor parameter is the list of _allowed_ methods
		return HttpResponseNotAllowed(['POST'], message)
	try:
		metric_id = request.POST['metric_id']
		# Don't have to select_subclasses() here,
		# active is defined on the base model.
		metric = Metric.objects.get(id=metric_id)
	except (ValueError, Metric.DoesNotExist):
		print('Malformed request')
		message = '400 - Malformed request.'
		return HttpResponseBadRequest(message)
	metric.active = False
	metric.save()
	return JsonResponse({'success': True})

def latest_sprint_badge(request, team_name=None):
	all_metrics = Metric.objects.filter(active=True).select_subclasses()
	last_sprint = conf.sprints[-1]
	if team_name is None:
		sum_score = 0
		for t in conf.teams:
			sum_score += Metric.rate(all_metrics, last_sprint, t)
		score = sum_score/len(conf.teams)
		extra_text = ''
	else:
		team = [t for t in conf.teams if t["name"] == team_name][0]
		score = Metric.rate(all_metrics, last_sprint, team)
		extra_text = '_--_' + team_name
	
	colors = {
		100: 'brightgreen', 80: 'green', 60: 'yellowgreen',
		40: 'yellow', 20: 'orange', 0: 'red'}
	current_color = colors[floor_to_multiple(score, multiple=20)]

	shields_io_url = 'https://img.shields.io/badge/{subject}-{status:.1f}-{color}.svg'
	subject = 'ScrumLint' + extra_text
	badge_url = shields_io_url.format(subject=subject, status=score, color=current_color)
	image = requests.get(badge_url)
	
	return HttpResponse(image.content, content_type="image/svg+xml")

metricsapp/templates/metricsapp/base.html
{% extends 'bootstrap3/bootstrap3.html' %}

{% load url from future %}
{% load bootstrap3 %}
{% load staticfiles %}

{% block bootstrap3_extra_head %}
	<!-- Base includes -->
	<link rel="stylesheet" type="text/css" href="{% static "metricsapp/style.css" %}">
	<script type="text/javascript" src="{% static "metricsapp/Chart.min.js" %}"></script>
	<!-- Additional includes -->
    {% block additional_head_includes %}
    {% endblock %}
{% endblock %}

{% block bootstrap3_title %}
ScrumLint
{% endblock %}

{% block bootstrap3_content %}
    <div class="container">
        {% bootstrap_messages %}

        {% block content %}(no content){% endblock %}
    </div>
{% endblock %}

metricsapp/templates/metricsapp/index.html
{% extends 'metricsapp/base.html' %}

{% load bootstrap3 %}
{% load artifactformat %}
{% load staticfiles %}

{% block additional_head_includes %}
	<script type="text/javascript" src="{% static "metricsapp/jquery.bootstrap-growl.min.js" %}"></script>
	<script type="text/javascript" src="{% static "metricsapp/index.js" %}"></script>
{% endblock %}

{% block content %}

<div class="well menu" id="sprint-nav">
	<ul class="nav nav-pills float-left">
		{% for sprint in sprint_list %}
			<li role="presentation" {% if current_sprint == sprint %}class="active"{% endif %}><a href="/sprint/{{ forloop.counter }}/team/{{ current_team.name }}">{{ sprint }}</a></li>
		{% endfor %}
	</ul>
	<a href="/compare/sprint/{{ current_sprint_index }}" id="compare-teams-btn" class="btn btn-info" role="button"><span class="glyphicon glyphicon-retweet" aria-hidden="true"></span> Compare teams in {{current_sprint}}</a>
	<div class="spacer"></div>
</div>

<div class="well menu">
	<ul class="nav nav-pills">
		{% for team in team_list %}
			<li role="presentation" {% if current_team.name == team.name %}class="active"{% endif %}><a href="/sprint/{{ current_sprint_index }}/team/{{ team.name }}" {% if current_team.name == team.name %}style="background-color: {{ team.label_color }}"{% endif %}>{{ team.name }}</a></li>
		{% endfor %}
	</ul>
</div>

<div class="jumbotron" id="score_keeper">
	<h2><strong>ScrumLint score</strong> of <br><a href="https://github.com/hpi-swt2/event-und-raumplanung" target="_blank">event-und-raumplanung</a>:</h2>
	<div id="radar-container">
		<canvas id="radar" data-labels="{{ chart_radar_labels }}" data-color="{{ current_team.label_color }}" data-scores="{{ chart_radar_data }}"></canvas>
	</div>
	<h1>{{ current_sprint_score|floatformat:2 }}<small>/100</span></small></h1>
	{# Only show line chart if there are more than two datapoints, i.e. sprints #}
	{% if current_sprint_index > 1 %}
		<div id="overall-chart-container">
			<canvas id="overall" data-labels="{{ chart_overall_labels }}" data-color="{{ current_team.label_color }}" data-scores="{{ chart_overall_data }}"></canvas>
		</div>
	{% endif %}
</div>

<div class="page-header">
	<h1>Details <small>How the score is calculated</a></small></h1>
</div>
{% if categories_list %}
	<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

		{% for container in categories_list|dictsort:"score" %}
			<h3>{{ container.categories.name }} <small>({{ container.score }})</small></h3>

			{% for metric, summary, previous in container.metrics|dictsort:"1.score" %}
				<div class="panel panel-default">
					<div class="panel-heading score-{{ summary.score|floor_to_multiple:'10'|floatformat:'0' }}" role="tab" id="heading{{ container.categories.name|slugify }}{{ forloop.counter }}">
						<h4 class="panel-title">
							<a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#{{ container.categories.name|slugify }}-{{ metric.name|slugify }}" aria-expanded="false" aria-controls="collapse{{ container.categories.name|slugify }}{{ forloop.counter }}">
								<span class="metric-score">{{ summary.score|floatformat }}</span><small>/100</small> <span class="metric-name">{{ metric.name }}</span> <small>{{ metric.description }}</small>
							</a>
						</h4>
					</div>
					<div id="{{ container.categories.name|slugify }}-{{ metric.name|slugify }}" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading{{ container.categories.name|slugify }}{{ forloop.counter }}">
						<div class="panel-body">
							<div class="well">
								<p>{{ metric.explanation|safe|linebreaks }}</p>
								<p>Importance: <strong>{{ metric.get_severity_display }}</strong> (influences the ScrumLint score with a factor of <strong>{{ metric.severity|floatformat:'-1' }}</strong>)
								<button type="button" class="btn btn-warning btn-xs metric-btn" data-toggle="modal" data-target="#deactive-metric-modal" data-metric-id="{{ metric.id }}" data-metric-name="{{ metric.name }}"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span> Deactivate metric</button>
								<a href="/compare/sprint/{{current_sprint_index}}#{{metric.name|slugify}}" class="btn btn-info btn-xs metric-btn" role="button"><span class="glyphicon glyphicon-retweet" aria-hidden="true"></span> Compare teams</a>
								<a href="{% url 'admin:metricsapp_metric_change' metric.id %}" class="btn btn-default btn-xs metric-btn" role="button"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Edit metric</a>
							</div>
							<table class="table">
								<tr>
									{% for header in summary.data.columns %}
										<th>{{ header|un_underscore}}</th>
									{% endfor %}
								</tr>
								{% for row in summary.data.rows %}
									<tr>
										{% for data in row %}
											<td>{{ data|format_artifact }}</td>
										{% endfor %}
									</tr>
								{% empty %}
									<tr><td colspan="100%">No results available.</td></tr>
								{% endfor %}
							</table>
							{# Only show line chart if there are more than two datapoints, i.e. sprints #}
							{% if current_sprint_index > 1 %}
								<div class="metric-chart-container">
									<canvas data-scores="{{ previous|safe }}" data-color="{{ current_team.label_color }}" class="metric-chart" id="chart-{{ container.categories.name|slugify }}-{{ metric.name|slugify }}"></canvas>
								</div>
							{% endif %}
							<p>Time since last update: {{ metric.last_query|timesince }}</p>
						</div>
					</div>
				</div>
			{% endfor %}
		{% endfor %}

	</div>
{% else %}
	<p>No metrics are available.</p>
{% endif %}

<!-- Modal -->
<div class="modal fade" id="deactive-metric-modal" tabindex="-1" role="dialog" aria-labelledby="modal-label" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="modal-label">Confirm</h4>
			</div>
			<div class="modal-body">
				<p>
					The metric <strong><span id="modal-metric-name">Forgotten Ones<span></strong> will be deactivated.<br>
					It will no longer influence the ScrumLint score.<br>
					<i>However, It can be reactivated later in the <a href="admin/metricsapp/metric/" target="_blank">administrative view</a></i>.<br>
				</p>
				<p>Are you sure?</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				<button type="button" class="btn btn-primary" id="deactivate-btn">Deactivate</button>
			</div>
		</div>
	</div>
</div>

{% endblock %}{# content#}